name: CSMC
main: top.scfd.mcplugins.csmc.CSMCPlugin
version: ${version}
api-version: ${apiVersion}
author: scfd
website: https://example.invalid
load: POSTWORLD
commands:
  csmc:
    description: CSMC session command
    usage: /csmc create <mode> | /csmc start
